version: 2
jobs:
  examples:
    docker:
      - image: modm/modm-build:latest
    steps:
      - checkout
      - run: pip3 install -U lbuild
      - run: (cd example/vendor && lbuild init)
      - run:
          name: Vendor Example
          command: |
            (cd example/vendor && lbuild build && scons)
      - run:
          name: MPU Class Example
          command: |
            (cd example/mpu_class && lbuild build && scons)

workflows:
  version: 2
  build:
    jobs:
      - examples
